// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfVUz2ZdH4P_yDZV0-F49gQ4yuYleE1yc',
    appId: '1:788827483235:web:bc2a3cc902836cd9c89c56',
    messagingSenderId: '788827483235',
    projectId: 'metchik',
    authDomain: 'metchik.firebaseapp.com',
    storageBucket: 'metchik.firebasestorage.app',
    measurementId: 'G-34CTKF8NZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqh1SJKuNfWuaQig58h4y0kleWTEHQfRg',
    appId: '1:788827483235:android:869c36ebc419b6e7c89c56',
    messagingSenderId: '788827483235',
    projectId: 'metchik',
    storageBucket: 'metchik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLjNiYRatiowyds1g1nfwATxDEZtWkFLc',
    appId: '1:788827483235:ios:3741773e02df4109c89c56',
    messagingSenderId: '788827483235',
    projectId: 'metchik',
    storageBucket: 'metchik.firebasestorage.app',
    iosBundleId: 'com.example.metchik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLjNiYRatiowyds1g1nfwATxDEZtWkFLc',
    appId: '1:788827483235:ios:3741773e02df4109c89c56',
    messagingSenderId: '788827483235',
    projectId: 'metchik',
    storageBucket: 'metchik.firebasestorage.app',
    iosBundleId: 'com.example.metchik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfVUz2ZdH4P_yDZV0-F49gQ4yuYleE1yc',
    appId: '1:788827483235:web:6edc03a268423f22c89c56',
    messagingSenderId: '788827483235',
    projectId: 'metchik',
    authDomain: 'metchik.firebaseapp.com',
    storageBucket: 'metchik.firebasestorage.app',
    measurementId: 'G-PBNL2KL11V',
  );
}
